### ISSUE TITLE
When using a SPARQL example, the title of the new tab should reflect the comment of the query example

### ISSUE THREAD

**Issue by JervenBolleman** [sib-swiss/sparql-editor#6]

**Comment by vemonet** [comment]
Just using the query comment is easy but would make every tab way too long:

![image](https://github.com/user-attachments/assets/5d3bea4a-fe9d-4e61-ab86-34b3189176b6)

We can try to automatically generate a 3 words description (e.g. here by filtering out all words smaller than 3 characters and a list of stopwords like `find, list, using...`)

Automatically generating a 2/3 words summarized description might be a solution

![image](https://github.com/user-attachments/assets/4f73c9b8-b571-4ed1-9a95-f1d37342076d)

What do you think of this? @JervenBolleman 

Note that I plan to make some changes to the UI: the tabs will probably go full width, with the examples alongside the endpoint input + editor

Maybe in the future we will be able to access local LLM models to do this on the client with `window.ai`, chrome is experimenting with this in canary

**Comment by vemonet** [comment]
This has been added in the latest release (0.2.0+) 

There are probably some stop words I did not think about, so feel free to let me know when you encounter some that would be nice to ignore
